version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-prueba-mario-manzanarez
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data:
